- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: debug, tags: debug}
#    - { role: common}

- hosts: workstation
  gather_facts: yes
  become: yes
  roles:
    - { role: storage}
