- name: Tools
  yum:
    name: "{{ packages }}"
  vars:
    packages:
     - vim
     - htop
     - "@Development tools"
     - yum-utils
     - device-mapper-persistent-data
     - lvm2
     - wget
     - curl
     - dstat
     - ddrescue
     - elinks
     - iotop
     - sysstat
